### ISSUE TITLE
Why are there 2 instances of telegraf?

### ISSUE THREAD

**Issue by ziffusion** [jersonmartinez/docker-compose-influxdb-telegraf-grafana#10]
This is not mentioned anywhere in the README and the configurations seem pretty similar. What is the reason for having two instances of telegraf?

**Comment by jersonmartinez** [comment]
There are two configuration files for containers.
3 more files for WSL, Windows OS and GNU/Linux. 

I still don't understand about the two instances you are talking about. In the future I want to do something more for this issue of instances in AWS, but I still do not have the time.

Please explain me better.

**Comment by ziffusion** [comment]
In the docker compose file, there are 2 instances of telegraf configured.

[telegraf](https://github.com/jersonmartinez/docker-compose-influxdb-telegraf-grafana/blob/26946aa147164fdf80054fe530a6947cf2ad927c/docker-compose.yml#L2)

[telegraf_second](https://github.com/jersonmartinez/docker-compose-influxdb-telegraf-grafana/blob/26946aa147164fdf80054fe530a6947cf2ad927c/docker-compose.yml#L20)

```
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    ...

  telegraf_second:
    image: telegraf
    container_name: telegraf_second
    restart: always
    ...
```

**Comment by jersonmartinez** [comment]
That's right, these are for both containers.

**Comment by ziffusion** [comment]
Dude, you asked me to explain better what I mean by "2 instances of telegraf" in the issue write-up. I did, and you come back with "yes, they are both containers"! The question was, why are there 2 instances of telegraf running? Do you even understand what all this is about, at all?

**Comment by jersonmartinez** [comment]
@ziffusion Because the Telegraf agent has to be running in each container to monitor the same container. In this case, I only need to monitor each container, and there are 2 of them. One telegraf per installed container. 

Sorry, I don't want to sound redundant, what is the real doubt in all this? Although it seems to me that more than a doubt, you have an objection, if so, I would love to know your guess.

**Comment by ziffusion** [comment]
I am sorry, but this makes no sense at all. But it's fine.

**Comment by jersonmartinez** [comment]
It would be excellent if you could tell me which is the correct meaning you believe. Everything is done to improve, dear. @ziffusion

**Comment by ziffusion** [comment]
The problem is that whatever you are saying is not making sense to me. And I don't know how to understand it better. A single telegraf instance can have hundreds of inputs configured. The only difference between the 2 configurations of telegraf is that one has nginx in it.

Can you explain why you need 2 instances of telegraf to do whatever you need to do? Why is 1 not enough? That was the original question. Just trying to understand if there is some subtle reason why 2 are necessary.

**Comment by jersonmartinez** [comment]
I understand your concern about having two Telegraf instances. Here's an example of how you could configure everything using a single Telegraf instance in the docker-compose.yml file to monitor two containers:

First, make sure you have a single Telegraf instance in your docker-compose.yml file:

```yaml
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Mount the Telegraf config file
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount the Docker socket to collect Docker metrics
    depends_on:
      - influxdb
      - nginx
    links:
      - influxdb
      - nginx
    ports:
      - '8125:8125'  # Expose Telegraf's StatsD port
    networks:
      - monitoring  # Connect Telegraf to the monitoring network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Mount the Nginx config directory
    ports:
      - '8080:80'  # Expose Nginx on port 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - monitoring  # Connect Nginx to the monitoring network

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'  # Expose InfluxDB on port 8086
    volumes:
      - influxdb_data:/var/lib/influxdb  # Mount the InfluxDB data directory
    networks:
      - monitoring  # Connect InfluxDB to the monitoring network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb
    ports:
      - '3000:3000'  # Expose Grafana on port 3000
    volumes:
      - grafana_data:/var/lib/grafana  # Mount the Grafana data directory
    networks:
      - monitoring  # Connect Grafana to the monitoring network

volumes:
  grafana_data: {}  # Volume for Grafana data
  influxdb_data: {}  # Volume for InfluxDB data

networks:
  monitoring:
    external: true  # Use an external network named 'monitoring'
```

Then, adjust the Telegraf configuration file (telegraf/telegraf.conf) to monitor both containers:

```yaml
# telegraf.conf file

# Global tags applied to all metrics
[global_tags]
  customer = "DevOpsea"
  environment = "Dev"
  os = "Linux"

# Agent configuration
[agent]
  interval = "60s"                 # Data collection interval
  round_interval = true           # Round collection interval
  metric_batch_size = 1000        # Max number of metrics per batch
  metric_buffer_limit = 10000     # Max number of metrics to keep in memory
  collection_jitter = "0s"        # Add jitter to avoid load spikes
  flush_interval = "10s"          # Data flush frequency to output plugins
  flush_jitter = "0s"             # Add jitter to flush to avoid load spikes
  precision = ""                  # Timestamp precision
  hostname = "docker-telegraf"    # Override default hostname
  omit_hostname = false           # Include hostname in metrics

# Output plugin configuration for InfluxDB
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]  # InfluxDB server URL
  database = "influx"              # Database name
  timeout = "5s"                   # HTTP request timeout
  username = "admin"               # InfluxDB username
  password = "admin"               # InfluxDB password

# Input plugin for collecting Nginx metrics
[[inputs.nginx]]
  urls = ["http://nginx/nginx_status"]  # URL for Nginx status page

# Input plugin for collecting CPU metrics
[[inputs.cpu]]
  percpu = true                    # Collect per CPU metrics
  totalcpu = true                  # Collect total CPU metrics
  collect_cpu_time = false        # Do not collect CPU time metrics
  report_active = false           # Do not report active CPU time

# Input plugin for collecting Docker metrics
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = ["nginx", "other_service_container"]  # Add the container names you want to monitor
  timeout = "5s"
```

This configuration uses a single Telegraf instance to collect system metrics, Docker metrics, and Nginx metrics. This way, you can monitor multiple containers with just one Telegraf instance.

I hope this clears up your question and is helpful. If you have more doubts or need further details, feel free to let me know.
